#!/usr/bin/env node
var fs = require('fs');
var mailerPath = __dirname + '/hooks/mailer.json';
var bakPath = mailerPath+'.bak'
var old = require(mailerPath);

function bak() {
    fs.writeFileSync(bakPath, JSON.stringify(old, null, 2));
}

var next = old.slice(0);

function add (name, mail) {
    if(!next.find( function(a) {return a.mail == mail} )) {
        console.log(name, mail);
        next.push({name: name, mail: mail});
    }
}

function save() {
    bak();
    fs.writeFileSync(mailerPath, JSON.stringify(next, null, 2));
}

// a.forEach(a=>add(a.name, a.mail));
if ( process.argv.slice(2).includes('-b') ) {
    fs.createReadStream(bakPath).pipe(fs.createWriteStream(mailerPath));
} else {
    var arr = process.argv.slice(2, 4);
    if (arr.length === 2) {
        if (/\w+@\w+\.\w+/.test(arr[1])) {
            add(arr[0], arr[1]);
        }
        save();
    }
}